---
version: '3.9'
services:
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock
    volumes:
      - $PWD/wiremock:/home/wiremock
      - ./__files/:/home/wiremock/__files
      - ./mappings/:/home/wiremock/mappings
    ports:
      - 8080:8080
    command: 
      - --global-response-templating
      - --verbose
      - --record-mappings
      